---
version: '3'
services:
  node0:
    build:
      context: .
      dockerfile: containers/Dockerfile
    volumes:
      - .:/usr/src/app
      - storage0:/usr/src/storage
    environment:
      - HOSTNAME=node0
      - PORT
      - NUMBER_OF_NODES
      - ELECTION_TIMEOUT_LOWER_MS
      - ELECTION_TIMEOUT_UPPER_MS
      - HEARTBEAT_TIMEOUT_MS
      - ITERATION_SLEEP_TIME_MS
  node1:
    build:
      context: .
      dockerfile: containers/Dockerfile
    volumes:
      - .:/usr/src/app
      - storage1:/usr/src/storage
    environment:
      - HOSTNAME=node1
      - PORT
      - NUMBER_OF_NODES
      - ELECTION_TIMEOUT_LOWER_MS
      - ELECTION_TIMEOUT_UPPER_MS
      - HEARTBEAT_TIMEOUT_MS
      - ITERATION_SLEEP_TIME_MS
  node2:
    build:
      context: .
      dockerfile: containers/Dockerfile
    volumes:
      - .:/usr/src/app
      - storage2:/usr/src/storage
    environment:
      - HOSTNAME=node2
      - PORT
      - NUMBER_OF_NODES
      - ELECTION_TIMEOUT_LOWER_MS
      - ELECTION_TIMEOUT_UPPER_MS
      - HEARTBEAT_TIMEOUT_MS
      - ITERATION_SLEEP_TIME_MS

volumes:
  storage0:
  storage1:
  storage2:


