---
version: '3'
services:
  node0:
    build:
      context: ./raft
      dockerfile: Dockerfile
    volumes:
      - ./raft:/usr/src/app
      - storage0:/usr/src/storage
    environment:
      - HOSTNAME=node0
      - PORT
      - NUMBER_OF_NODES
      - ELECTION_TIMEOUT_LOWER_MS
      - ELECTION_TIMEOUT_UPPER_MS
      - HEARTBEAT_TIMEOUT_MS
      - ITERATION_SLEEP_TIME_MS
  node1:
    build:
      context: ./raft
      dockerfile: Dockerfile
    volumes:
      - ./raft:/usr/src/app
      - storage1:/usr/src/storage
    environment:
      - HOSTNAME=node1
      - PORT
      - NUMBER_OF_NODES
      - ELECTION_TIMEOUT_LOWER_MS
      - ELECTION_TIMEOUT_UPPER_MS
      - HEARTBEAT_TIMEOUT_MS
      - ITERATION_SLEEP_TIME_MS
  node2:
    build:
      context: ./raft
      dockerfile: Dockerfile
    volumes:
      - ./raft:/usr/src/app
      - storage2:/usr/src/storage
    environment:
      - HOSTNAME=node2
      - PORT
      - NUMBER_OF_NODES
      - ELECTION_TIMEOUT_LOWER_MS
      - ELECTION_TIMEOUT_UPPER_MS
      - HEARTBEAT_TIMEOUT_MS
      - ITERATION_SLEEP_TIME_MS
  node3:
    build:
      context: ./raft
      dockerfile: Dockerfile
    volumes:
      - ./raft:/usr/src/app
      - storage3:/usr/src/storage
    environment:
      - HOSTNAME=node3
      - PORT
      - NUMBER_OF_NODES
      - ELECTION_TIMEOUT_LOWER_MS
      - ELECTION_TIMEOUT_UPPER_MS
      - HEARTBEAT_TIMEOUT_MS
      - ITERATION_SLEEP_TIME_MS
  node4:
    build:
      context: ./raft
      dockerfile: Dockerfile
    volumes:
      - ./raft:/usr/src/app
      - storage4:/usr/src/storage
    environment:
      - HOSTNAME=node4
      - PORT
      - NUMBER_OF_NODES
      - ELECTION_TIMEOUT_LOWER_MS
      - ELECTION_TIMEOUT_UPPER_MS
      - HEARTBEAT_TIMEOUT_MS
      - ITERATION_SLEEP_TIME_MS

  client:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - ./application:/usr/src/app
    environment:
      - HOSTNAME=client
      - PORT
      - NUMBER_OF_NODES
      - CLIENT_RETRY_TIMEOUT_MS

volumes:
  storage0:
  storage1:
  storage2:
  storage3:
  storage4:


