---
version: '3'
services:
  node0:
    build:
      context: .
      dockerfile: containers/Dockerfile
    volumes:
      - .:/usr/src/app
      - storage0:/usr/src/storage
    environment:
      - HOSTNAME=node0
      - PORT
      - NUMBER_OF_NODES
  node1:
    build:
      context: .
      dockerfile: containers/Dockerfile
    volumes:
      - .:/usr/src/app
      - storage1:/usr/src/storage
    environment:
      - HOSTNAME=node1
      - PORT
      - NUMBER_OF_NODES

volumes:
  storage0:
  storage1:


