---
version: '3'
services:
  app1:
    build:
      context: .
      dockerfile: containers/Dockerfile
    volumes:
      - .:/usr/src/app
      - storage1:/usr/src/storage
    environment:
      - HOSTNAME=app1
      - PORT=3131
  app2:
    build:
      context: .
      dockerfile: containers/Dockerfile
    volumes:
      - .:/usr/src/app
      - storage2:/usr/src/storage
    environment:
      - HOSTNAME=app2
      - PORT=3131

volumes:
  storage1:
  storage2:
